---
title: "2021-08-31 TidyTuesday Birds Bath"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Loading Libraries

```{r loading_libraries}
suppressMessages({
  library(tidyverse)
  library(scales)
  library(hrbrthemes)
  library(ggtext)
  library(glue)
  library(tidytuesdayR)
  library(skimr)
})
```

```{r plot_theme, echo = FALSE}
theme_set(
  theme_ipsum_rc(grid = 'Y') +
    theme(
      plot.title.position = 
        "plot",
      plot.margin = 
        margin(25,25,25,25),
      axis.title.x = 
        element_markdown(
          hjust = .5, size = 12, margin = margin(t = 15, r = 00, b = 0, l = 0)),
      axis.title.y = 
        element_markdown(
          hjust = .5, size = 12, margin = margin(t = 0, r = 15, b = 0, l = 0)),
      plot.subtitle = 
        element_markdown(family = 'Roboto Condensed', color = 'grey60'),
      strip.text = 
        element_text(hjust = .5, color = 'grey60', size = 10)
    )
)

```

### Loading this week data

```{r message=FALSE, warning=FALSE}
bird_baths <- read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data//2021/2021-08-31/bird_baths.csv')
```

------------------------------------------------------------------------

### Data Overview

```{r}
skimr::skim(bird_baths)
```

------------------------------------------------------------------------
### Manipulating Data
```{r fig.width=5*2, fig.height=3*2}
data2plot <-
  bird_baths %>%
  filter(complete.cases(.)) %>%
  group_by(bird_type, urban_rural, survey_year) %>% 
  summarise(n = sum(bird_count)) %>%
  pivot_wider(names_from = urban_rural, values_from = n) %>%
  mutate(pct_urban = Urban/(Rural+Urban)) %>%
  filter(Urban > 0 & Rural > 0) %>%
  group_by(bird_type) %>%
  filter(n() == 2) %>%
  ungroup()
```

- Calculate `pct_urban` variation (delta)

```{r fig.width=5*2, fig.height=3*2}
my_order <-
  data2plot %>%
  mutate(survey_year = as.character(survey_year)) %>%
  select(-Rural, -Urban) %>%
  pivot_wider(names_from = survey_year, values_from = pct_urban) %>%
  mutate(delta = `2014`-`2015`)
```


- Classifying birds (lazy way, sorry)

```{r fig.width=5*2, fig.height=3*2}
moving_to_city <-
  my_order %>%
  filter(delta < 0) %>%
  pull(bird_type)

moving_to_camp <-
  my_order %>%
  filter(delta > 0) %>%
  pull(bird_type)
```

- Creating list with top 10 most spotted birds going to camp and top 10 going to city (lazy again)

```{r fig.width=5*2, fig.height=3*2}
allow_list_bird_moving_to_city <-
  data2plot %>%
  filter(bird_type %in% moving_to_city) %>%
  mutate(n = Rural + Urban) %>%
  group_by(bird_type) %>%
  summarise(total_n = sum(n)) %>%
  slice_max(total_n, n = 10, with_ties = FALSE) %>%
  pull(bird_type) %>% unique()

allow_list_bird_moving_to_camp <-
  data2plot %>%
  filter(bird_type %in% moving_to_camp) %>%
  mutate(n = Rural + Urban) %>%
  group_by(bird_type) %>%
  summarise(total_n = sum(n)) %>%
  slice_max(total_n, n = 10, with_ties = FALSE) %>%
  pull(bird_type) %>% unique()
```

- Creating final ordering

```{r fig.width=5*2, fig.height=3*2}
my_order <-
  my_order %>%
  filter(
    bird_type %in% c(allow_list_bird_moving_to_city, allow_list_bird_moving_to_camp)) %>%
  arrange(delta) %>%
  pull(bird_type) %>% 
  unique()
```

- Plotting!

```{r fig.width=5*2, fig.height=3*2}
data2plot %>%
  filter(
    bird_type %in% c(allow_list_bird_moving_to_city, allow_list_bird_moving_to_camp)) %>%
  mutate(survey_year = as.character(survey_year)) %>%
  mutate(moving = if_else(bird_type %in% allow_list_bird_moving_to_city, 'Moving to city bird baths', 'Moving to camp bird baths')) %>%
  mutate(moving = toupper(moving)) %>%
  ggplot(aes(x = factor(bird_type, levels = c(my_order)), y = pct_urban, )) +
  geom_point(size = 4, aes(color = survey_year), alpha = .3) +
  geom_line(aes(group = bird_type), color = 'black', size = .5,
            arrow = arrow(length=unit(0.10,"cm"), ends="last", type = "closed")) +
  geom_hline(yintercept = 0.5, color = 'grey60') +
  facet_wrap(. ~ moving, scales = 'free_y') +
  scale_y_continuous(limits = c(0,1), labels = scales::percent) +
  coord_flip() +
  labs(x = NULL, y = "**Birds spotted in cities bird baths** (%)", title = "Moving Out!",
       subtitle = "Some birds decided to find a new place to bathe in 2015.",
       color = NULL,
       caption = '#TidyTuesday / 2021.08.31 / Bird species were filtered by highest birds spotted') +
  ggthemes::scale_color_calc() +
  theme(legend.position = 'bottom')
```

- Save plot

```{r fig.width=5*2, fig.height=3*2}
ggsave(
  filename = "tidytuesday_2021-08-31.png",
  device = "png",width = 5*2, height = 3*2, bg = '#f0eeeb')  
```
